# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/environment.yml

build:
  image: latest

python:
  version: 3.8

