package:
  name: "pynsee"
  version: "0.1.1"

source:
  git_rev: v0.1.1
  git_url: https://github.com/InseeFrLab/pynsee

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - pandas
    - requests>=2.23
    - tqdm>=4.56.0
    - appdirs>=1.4.4
    - unidecode>=1.1.0
    - shapely>=1.8.0,<2.0
    - pathlib

about:
  home: https://github.com/InseeFrLab/pynsee
  license: OPEN LICENCE 2.0/LICENCE OUVERTE 2.0
  license_familY: MIT
  license_file: LICENSE
  summary: "Tools to Easily Search and Download French Data From INSEE and IGN APIs"

extra:
  recipe-maintainers:
    - hadrilec