name: Examples test

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        #sudo apt-get install libgeos-dev
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov geopandas nbconvert matplotlib descartes  
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Test idbank list download
      env:      
        insee_key: ${{ secrets.INSEE_KEY }}
        insee_secret: ${{ secrets.INSEE_SECRET }}
      run: |     
        pip install . 
        pytest ./tests/macrodata/test_pynsee_macrodata.py::TestFunction::test_download_series_list

    - name: Test all examples
      env:
        insee_key: ${{ secrets.INSEE_KEY }}
        insee_secret: ${{ secrets.INSEE_SECRET }}
      run: |
        pip install jupytext
        pip install . 
        pip install -r docs/requirements.txt            
        # test all notebooks        
        cd docs/examples 
        jupytext --to py *.ipynb
        # run all py files
        for f in *.py; do python "$f"; done
        cd ../..
    
