name: Deploy as website

on:
  push:
    branches:
      - main
      - master
      - usequarto

jobs:
  build:
    runs-on: ubuntu-latest
    container: inseefrlab/pynsee:latest
    steps:
      - uses: actions/checkout@v3
      - name: Render site
        env:
          insee_key: ${{ secrets.INSEE_KEY }}
          insee_secret: ${{ secrets.INSEE_SECRET }}
        run: |
          pip install -r docs/requirements.txt
          cd docs/examples/
          quarto render example_download.qmd
      - uses: actions/upload-artifact@v1
        with:
          name: Report
          path: |
            example_download.ipynb
            example_download.html